# Generated by Django 3.2.dev20200814111336 on 2020-08-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
