# Generated by Django 3.2.dev20200814111336 on 2020-08-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.CharField(default='User not found', max_length=200),
        ),
    ]
